name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Endor Labs Scan
      uses: endorlabs/github-action@v1.1.4
      with:
        namespace: "contoso-hotels"
        api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
        api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
        enable_github_action_token: false
            
