name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.REGISTRY_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -f ./Dockerfile -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest .

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest

    - name: Endor Labs Scan
      uses: endorlabs/github-action@v1.1.4
      with:
        namespace: "contoso-hotels"
        scan_dependencies: false
        scan_container: true
        image: myapp:latest
        project_name: contoso/vulngraphql
        api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
        api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
        enable_github_action_token: false
